#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 19 15:32:07 2017

@author: apple
"""
# factorial
def factorial(n):
    if n <= 1:
        return n
    else:
        return n*factorial(n-1)

def main():
    number = int(input('Enter a nonnegative integer: '))
    fact = factorial(number)
    print('The factorial of', number, 'is', fact)
    
main()


# OOP student class
class Student:
    def __init__(self, name = "", class_of = 0, major = ""):
        self.name = name
        self.class_of = class_of
        self.major = major
        self.knowledge = 0
    
    def get_name(self):
        return self.name

    def set_name(self,name):
        self.name = name

    def get_knowledge(self):
        return self.knowledge
    
    # method
    def study(self, time_s):
        self.knowledge += 1.5 * time_s